#!/bin/sh

# git executable wrapper script for Git-Mediawiki to run tests without
# installing the scripts in Git's exec path.

ROOT_DIR=$(dirname "$0")/..

PATH="$ROOT_DIR:$PATH"

export PATH

exec "${GIT_EXEC_PATH:-/usr/bin/}git" "$@"
